<a href="https://colab.research.google.com/github/lixinso/sample-intro-to-pytorch/blob/master/distribution_Normal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
from torch.distributions.normal import Normal

In [5]:
m = Normal(torch.tensor([0.0]), torch.tensor([1.0]))
m.sample() 

tensor([-0.7598])

In [6]:
dir(m)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_batch_shape',
 '_event_shape',
 '_extended_shape',
 '_get_checked_instance',
 '_log_normalizer',
 '_mean_carrier_measure',
 '_natural_params',
 '_validate_args',
 '_validate_sample',
 'arg_constraints',
 'batch_shape',
 'cdf',
 'entropy',
 'enumerate_support',
 'event_shape',
 'expand',
 'has_enumerate_support',
 'has_rsample',
 'icdf',
 'loc',
 'log_prob',
 'mean',
 'perplexity',
 'rsample',
 'sample',
 'sample_n',
 'scale',
 'set_default_validate_args',
 'stddev',
 'support',
 'variance']

In [7]:
m.scale

tensor([1.])

In [8]:
m.loc

tensor([0.])

In [9]:
m.stddev

tensor([1.])

In [10]:
m.variance

tensor([1.])

In [11]:
m.mean

tensor([0.])