<a href="https://colab.research.google.com/github/lixinso/sample-intro-to-pytorch/blob/master/MSELoss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch.nn as nn
import torch

In [12]:
A = torch.randn([2, 14])
A

tensor([[-0.5919, -1.1840, -1.3685,  0.2383, -0.7372, -1.1504,  0.3397,  1.3020,
          0.3166, -0.3053,  1.4559,  0.9601, -0.6443,  0.4933],
        [ 0.3585,  0.2000, -1.2419,  0.3809, -1.6868,  1.1564,  2.0062,  0.3639,
         -0.3848,  2.1135,  2.4622, -0.8249, -0.2167, -1.8941]])

In [13]:
B = torch.randn([2, 14])
B

tensor([[-1.1433, -0.7849, -0.3413, -0.2473, -2.3327, -0.0731, -0.2575, -0.3972,
         -1.7071,  1.8025,  1.9440, -1.7540, -0.7061, -1.1375],
        [ 0.4481, -1.4325,  0.2218,  0.3253,  1.4766,  0.4013,  0.3611,  0.6924,
         -0.8709,  1.6695,  1.1754,  1.0373, -0.5859, -0.0760]])

In [14]:
nn.MSELoss(A,B)

RuntimeError: ignored

In [15]:
loss1 = nn.MSELoss()
loss1(A,B)

tensor(1.9543)

In [16]:
#https://pytorch.org/docs/stable/nn.html
loss = nn.MSELoss()
#input = torch.randn(3, 5, requires_grad=True)
input = torch.randn(3, 5)
print(input)
target = torch.randn(3, 5)
print(target)
output = loss(input, target)
#output.backward()
print(output)

tensor([[-0.0050, -1.2103,  0.9540, -0.6561, -0.5217],
        [-0.4056,  0.4591,  0.9415,  0.5774, -0.2199],
        [-0.6606,  0.7710, -1.1262,  1.2495,  1.5977]])
tensor([[ 1.3077, -0.6210,  0.3232,  0.1827, -0.3173],
        [-2.3596, -0.4654, -0.0589, -1.9526,  1.3699],
        [-1.0124, -0.5670, -2.1607, -0.8146,  2.0108]])
tensor(1.6821)


In [17]:
output

tensor(1.6821)